### ISSUE TITLE
Service unavailable (503)

### ISSUE THREAD

**Issue by sthyregod** [docmeta/rubydoc.info#156]
I've been running into a few 503 errors when browsing the site, specifically when trying to browse the documentation on the following link:

https://www.rubydoc.info/github/rails/activeresource

![screenshot](https://i.imgur.com/adRiY04.png)

**Comment by whatisdot** [comment]
I also observed this yesterday afternoon (Apr 26).

@lsegal Did the hosting for rubydoc.info change recently?

**Comment by nateleavitt** [comment]
Also experiencing this with my own gem.

**Comment by lsegal** [comment]
There was an outage that seemed to be only affecting github projects. We investigated and it should now be resolved. Will be looking into how that happened. Thanks for reporting!

**Comment by Crusader500** [comment]
I am having this same issue please fix it

**Comment by pedrofurtado** [comment]
Still with error 😢

**Comment by lsegal** [comment]
We ran a quick restart on the service and it should be working now. We had an out of memory error which is pretty abnormal and will be investigating what caused it so we can fix and avoid this in the future.

Thanks for reporting!

**Comment by whatisdot** [comment]
@lsegal Looks like we're still seeing some disruption: https://rubydoc.info/gems/yard/File

**Comment by lsegal** [comment]
Thanks again! Made some adjustments just now to the memory usage so we can start working out how to better improve service.

Looks like people are catching this before our own uptime notifications are, so that's something we will also adjust.

**Comment by lsegal** [comment]
(PS: service is now functioning again)

**Comment by SampsonCrowley** [comment]
@lsegal down again

**Comment by SampsonCrowley** [comment]
@lsegal This seems to come back up with the same problem quite frequently. maybe it is time for a more robust resolution? (not that I have any suggestions without knowing what the original resolutions have been, every issue just says it's "being worked on", or "been fixed")

Very much appreciate the rubydocs service and would be willing to contribute to solving the solution in a more permanent manner if possible

https://github.com/docmeta/rubydoc.info/issues/53
https://github.com/docmeta/rubydoc.info/issues/109
https://github.com/docmeta/rubydoc.info/issues/122 (mentioned, not main issue)
https://github.com/docmeta/rubydoc.info/issues/124
https://github.com/docmeta/rubydoc.info/issues/134
https://github.com/docmeta/rubydoc.info/issues/147
https://github.com/docmeta/rubydoc.info/issues/158

**Comment by whatisdot** [comment]
I share @SampsonCrowley's thoughts. The rubydocs project is a tremendous help for my team.

I've spent the last 3-4 years designing and building the infrastructure at [Snapsheet](https://www.snapsheetclaims.com/), and I'd be happy to contribute any insights I have to finding a good solution for rubydocs hosting.

**Comment by svoop** [comment]
503 have become less frequent, but apparently, docs (most notably generated off GitHub main) are often garbled. I mention it here because it could be a memory issues as mentioned above.

@lsegal YARD is tremendously useful for the community! That said, maybe [Ruby Central](https://rubycentral.org/) would be willing to host (or sponsor the hosting) – maybe having more CPU and mem resource for rubydoc.info would help.

**Comment by lsegal** [comment]
Closing out some old issues that have likely been resolved since the original report. If this is still a problem please reopen, thanks!

(Note: this is a bulk message, apologies in advance if this feels impersonal)
